services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    develop:
      watch:
      - action: sync
        path: ./frontend
        target: ./app
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
      - action: sync
        path: ./backend
        target: ./backend